version: '3.9'

# Set a custom name for this volume.
volumes:
  grafana_data:
    name: grafana_data
  grafana_provisioning:
    name: grafana_provisioning
  grafana_plugins:
    name: grafana_plugins
    
networks:
  traefik:
    external: true

services:    
  grafana:
    image: grafana/grafana:11.2.0
    restart: always
    container_name: grafana
    ports:
      - 3000:3000
    expose: 
      - 3000
    networks:
      - traefik
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_ROOT_URL=https://grafana-docker-1.domain.com/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=Grafana
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
      # # GF_PATHS_PROVISIONING
      # # https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-grafana
      # - "grafana_provisioning:/etc/grafana/provisioning"
      # GF_PATHS_DATA
      - "grafana_data:/var/lib/grafana"
      # GF_PATHS_PLUGINS
      - "grafana_plugins:/var/lib/grafana/plugins"
    labels:
      # Dynamic configuration with Docker Labels
      # Ref: https://docs.traefik.io/reference/dynamic-configuration/docker/
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true   
      # The domain the service will respond to
      - traefik.http.routers.grafana-web-router.rule=Host(`grafana-docker-1.domain.com`)
      # Allow request only from the predefined entry point named "web" http port
      - traefik.http.routers.grafana-web-router.entrypoints=web
      # Set the service parameter on the router.
      - traefik.http.routers.grafana-web-router.service=grafana-web-service
      # Forwarding requests to more than one port on a container requires referencing the 
      # service loadbalancer port definition using the service parameter on the router.
      - traefik.http.services.grafana-web-service.loadbalancer.server.port=3000
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224 
        fluentd-async: 'true'
        # Tag for Fluent Bit to Loki
        tag: loki.grafana