{
 "title": "MinIO Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum(minio_bucket_usage_total_bytes{job=\"$scrape_jobs\"}) by (instance,server))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (range) (sum (minio_bucket_objects_size_distribution{job=\"$scrape_jobs\"}) by (range))",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (minio_node_file_descriptor_open_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (minio_node_go_routine_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Online Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_disk_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Total online disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bucket) (minio_bucket_usage_total_bytes{job=\"$scrape_jobs\"}))"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Offline Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_disk_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_bucket_usage_object_total{job=\"$scrape_jobs\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_heal_time_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_usage_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Bucket Traffic Sent",
   "type": "timeseries",
   "description": "Total s3 bytes sent per bucket",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Traffic Received",
   "type": "timeseries",
   "description": "Total s3 bytes received per bucket",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Internode Data Transfer",
   "type": "graph",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "rate(minio_inter_node_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Healing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (minio_heal_objects_heal_total{job=\"$scrape_jobs\"})",
     "legendFormat": "Objects healed in current self heal run"
    },
    {
     "expr": "sum by (instance) (minio_heal_objects_error_total{job=\"$scrape_jobs\"})",
     "legendFormat": "Heal errors in current self heal run"
    },
    {
     "expr": "sum by (instance) (minio_heal_objects_total{job=\"$scrape_jobs\"}) ",
     "legendFormat": "Objects scanned in current self heal run"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "CPU Usage Rate [{{server}}]"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Memory Used [{{server}}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_disk_used_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Used Capacity [{{server}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Drives Free Inodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_disk_free_inodes{job=\"$scrape_jobs\"}",
     "legendFormat": "Free Inodes [{{server}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "graph",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Node File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  }
 ]
}